name: Invoke Lambda with OIDC
 
on:
  schedule:
   - cron: '0 */2 * * *'
 
jobs:
  invoke-lambda:
    # 1) Grant OIDC permissions to request the ID token
    permissions:
      id-token: write
      contents: read
 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::908027376186:role/lambda_rol_invoke_function_cine_pos_data
          aws-region: us-east-1
 
      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name cine_pos_data \
            output.json
          echo "Lambda output:"
          cat output.json
